function sendEmail(subject)
% sendEmail function can send email by Matlab.
% email sender
sendMailAddress = 'youremail@mail.com';
% app-specific password 
% you need to create the app-specific password.
password = '';  
% gmail SMTP server
smtpServer = 'smtp.gmail.com';
% SMTP port
smtpPort = '587';
% configure SMTP server and account information
setpref('Internet','E_mail',sendMailAddress);
setpref('Internet','SMTP_Server', smtpServer);
setpref('Internet','SMTP_Username',sendMailAddress);
setpref('Internet','SMTP_Password',password);
props = java.lang.System.getProperties;
props.setProperty( 'mail.smtp.auth', 'true');
props.setProperty( 'mail.smtp.user', sendMailAddress);
props.setProperty( 'mail.smtp.password', password);
props.setProperty( 'mail.smtp.host', smtpServer);
props.setProperty( 'mail.smtp.port', smtpPort);
props.setProperty( 'mail.smtp.starttls.enable', 'true');

%% send email
% subject 
% subject = 'Generated by the AutoPatch';
% email content
content = 'Code execution complete!';
receiveMailAddress1='youremail@mail.com';
sendmail(receiveMailAddress1,subject,content);
% sendmail(receiveMailAddress2,subject,content, expLog);
end